version: '3.8'

services:
  master:
    image: mysql:8.0
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "33006:3306"
    volumes:
      - /home/binzou/mysql-cluster/master/data:/var/lib/mysql
      - /home/binzou/mysql-cluster/master/conf:/etc/mysql

  slave:
    image: mysql:8.0
    container_name: mysql-slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "33007:3306"
    depends_on:
      - master
    volumes:
      - /home/binzou/mysql-cluster/salve/data:/var/lib/mysql
      - /home/binzou/mysql-cluster/salve/conf:/etc/mysql
